var aplusSufeiId : string;
var beaconAplusId : string;
var isHomeId : string;
var webInfowsRegOriId : string;
var userDeviceTypeId : string;
var userCountryCodeId : string;
var userCountryNameId : string;
var isResponstiveHeaderId : string;
var monthId : string;
var dayId : string;
var isSellerId : string;
var aeTopBannerId : string;
var jSiteDownloadHeaderId : string;
var topLighthouseId : string;
var navGlobalId : string;
var switcherInfoId : string;
var switcherLanguageInfoId : string;
var siteNavGoogleTranslateId : string;
var google_translate_elementId : string;
var _0targetLanguageId : string;
var headerId : string;
var headerCategoriesId : string;
var navCartNumId : string;
var navWishlistCtnId : string;
var navWishListMsgId : string;
var navUserAccountId : string;
var flyoutRemindListId : string;
var formSearchbarId : string;
var catIdId : string;
var historyTabId : string;
var historySearchInputId : string;
var historySearchCountryId : string;
var initiative_idId : string;
var searchCateId : string;
var searchCategoryValueId : string;
var searchKeyId : string;
var homeFirstscreenId : string;
var keyVisualMainId : string;
var industryEntranceId : string;
var userBenefitsId : string;
var superdealsEntryId : string;
var brandZoneEntryId : string;
var industryFloorId : string;
var emergingStoreEntryId : string;
var historyRecordId : string;
var relatedRecommendEntryId : string;
var alertSubscribeFormId : string;
var newuserActivityConfigId : string;
var localstorageProxyIfrAlibabadotcomId : string;
var criteoTagsDivId : string;
var googGtTtId : string;
var _oid_ifr_Id : string;

var dataLocale : string;
var dataSpm : string;
var dataGrCSLoaded : string;
var dataWidgetCid : string;
var dataRole : string;
var dataSite : string;
var dataPath : string;
var dataOrder : string;
var dataLoaded : string;
var dataSrc : string;
var dataStat : string;
var dataWidgetid : string;
var dataSpaSurvive : string;
var dataTest : string;
var dataDealsLink : string;
var dataIswintertime : string;
var dataPhase : string;
var dataWidgetId : string;
var dataEmailerror : string;
var dataFailtips : string;
var dataSuccesstips : string;
var dataIsshowspecificuserdialog : string;
var dataAnimateimg : string;
var dataBtntext : string;
var dataCouponTitle : string;
var dataDenomination : string;
var dataFrequency : string;
var dataLayerbg : string;
var dataLink : string;
var dataPromotionname : string;
var dataSubtitle : string;
var dataTipsTitle : string;
var dataTitle : string;
var dataSpmAnchorId : string;
var dataSpmActId : string;

export class alliExpress {

    public aplusSufeiId: HTMLElement;
    public beaconAplusId: HTMLElement;
    public isHomeId: HTMLElement;
    public webInfowsRegOriId: HTMLElement;
    public userDeviceTypeId: HTMLElement;
    public userCountryCodeId: HTMLElement;
    public userCountryNameId: HTMLElement;
    public isResponstiveHeaderId: HTMLElement;
    public monthId: HTMLElement;
    public dayId: HTMLElement;
    public isSellerId: HTMLElement;
    public aeTopBannerId: HTMLElement;
    public jSiteDownloadHeaderId: HTMLElement;
    public topLighthouseId: HTMLElement;
    public navGlobalId: HTMLElement;
    public switcherInfoId: HTMLElement;
    public switcherLanguageInfoId: HTMLElement;
    public siteNavGoogleTranslateId: HTMLElement;
    public google_translate_elementId: HTMLElement;
    public _0targetLanguageId: HTMLElement;
    public headerId: HTMLElement;
    public headerCategoriesId: HTMLElement;
    public navCartNumId: HTMLElement;
    public navWishlistCtnId: HTMLElement;
    public navWishListMsgId: HTMLElement;
    public navUserAccountId: HTMLElement;
    public flyoutRemindListId: HTMLElement;
    public formSearchbarId: HTMLElement;
    public catIdId: HTMLElement;
    public historyTabId: HTMLElement;
    public historySearchInputId: HTMLElement;
    public historySearchCountryId: HTMLElement;
    public initiative_idId: HTMLElement;
    public searchCateId: HTMLElement;
    public searchCategoryValueId: HTMLElement;
    public searchKeyId: HTMLElement;
    public homeFirstscreenId: HTMLElement;
    public keyVisualMainId: HTMLElement;
    public industryEntranceId: HTMLElement;
    public userBenefitsId: HTMLElement;
    public superdealsEntryId: HTMLElement;
    public brandZoneEntryId: HTMLElement;
    public industryFloorId: HTMLElement;
    public emergingStoreEntryId: HTMLElement;
    public historyRecordId: HTMLElement;
    public relatedRecommendEntryId: HTMLElement;
    public alertSubscribeFormId: HTMLElement;
    public newuserActivityConfigId: HTMLElement;
    public localstorageProxyIfrAlibabadotcomId: HTMLElement;
    public criteoTagsDivId: HTMLElement;
    public googGtTtId: HTMLElement;
    public _oid_ifr_Id: HTMLElement;

    public dataLocale: JQuery<HTMLElement>;
    public dataSpm: JQuery<HTMLElement>;
    public dataGrCSLoaded: JQuery<HTMLElement>;
    public dataWidgetCid: JQuery<HTMLElement>;
    public dataRole: JQuery<HTMLElement>;
    public dataSite: JQuery<HTMLElement>;
    public dataPath: JQuery<HTMLElement>;
    public dataOrder: JQuery<HTMLElement>;
    public dataLoaded: JQuery<HTMLElement>;
    public dataSrc: JQuery<HTMLElement>;
    public dataStat: JQuery<HTMLElement>;
    public dataWidgetid: JQuery<HTMLElement>;
    public dataSpaSurvive: JQuery<HTMLElement>;
    public dataTest: JQuery<HTMLElement>;
    public dataDealsLink: JQuery<HTMLElement>;
    public dataIswintertime: JQuery<HTMLElement>;
    public dataPhase: JQuery<HTMLElement>;
    public dataWidgetId: JQuery<HTMLElement>;
    public dataEmailerror: JQuery<HTMLElement>;
    public dataFailtips: JQuery<HTMLElement>;
    public dataSuccesstips: JQuery<HTMLElement>;
    public dataIsshowspecificuserdialog: JQuery<HTMLElement>;
    public dataAnimateimg: JQuery<HTMLElement>;
    public dataBtntext: JQuery<HTMLElement>;
    public dataCouponTitle: JQuery<HTMLElement>;
    public dataDenomination: JQuery<HTMLElement>;
    public dataFrequency: JQuery<HTMLElement>;
    public dataLayerbg: JQuery<HTMLElement>;
    public dataLink: JQuery<HTMLElement>;
    public dataPromotionname: JQuery<HTMLElement>;
    public dataSubtitle: JQuery<HTMLElement>;
    public dataTipsTitle: JQuery<HTMLElement>;
    public dataTitle: JQuery<HTMLElement>;
    public dataSpmAnchorId: JQuery<HTMLElement>;
    public dataSpmActId: JQuery<HTMLElement>;

    public constructor() {
        this.aplusSufeiId = document.getElementById(aplusSufeiId)!;
        this.beaconAplusId = document.getElementById(beaconAplusId)!;
        this.isHomeId = document.getElementById(isHomeId)!;
        this.webInfowsRegOriId = document.getElementById(webInfowsRegOriId)!;
        this.userDeviceTypeId = document.getElementById(userDeviceTypeId)!;
        this.userCountryCodeId = document.getElementById(userCountryCodeId)!;
        this.userCountryNameId = document.getElementById(userCountryNameId)!;
        this.isResponstiveHeaderId = document.getElementById(isResponstiveHeaderId)!;
        this.monthId = document.getElementById(monthId)!;
        this.dayId = document.getElementById(dayId)!;
        this.isSellerId = document.getElementById(isSellerId)!;
        this.aeTopBannerId = document.getElementById(aeTopBannerId)!;
        this.jSiteDownloadHeaderId = document.getElementById(jSiteDownloadHeaderId)!;
        this.topLighthouseId = document.getElementById(topLighthouseId)!;
        this.navGlobalId = document.getElementById(navGlobalId)!;
        this.switcherInfoId = document.getElementById(switcherInfoId)!;
        this.switcherLanguageInfoId = document.getElementById(switcherLanguageInfoId)!;
        this.siteNavGoogleTranslateId = document.getElementById(siteNavGoogleTranslateId)!;
        this.google_translate_elementId = document.getElementById(google_translate_elementId)!;
        this._0targetLanguageId = document.getElementById(_0targetLanguageId)!;
        this.headerId = document.getElementById(headerId)!;
        this.headerCategoriesId = document.getElementById(headerCategoriesId)!;
        this.navCartNumId = document.getElementById(navCartNumId)!;
        this.navWishlistCtnId = document.getElementById(navWishlistCtnId)!;
        this.navWishListMsgId = document.getElementById(navWishListMsgId)!;
        this.navUserAccountId = document.getElementById(navUserAccountId)!;
        this.flyoutRemindListId = document.getElementById(flyoutRemindListId)!;
        this.formSearchbarId = document.getElementById(formSearchbarId)!;
        this.catIdId = document.getElementById(catIdId)!;
        this.historyTabId = document.getElementById(historyTabId)!;
        this.historySearchInputId = document.getElementById(historySearchInputId)!;
        this.historySearchCountryId = document.getElementById(historySearchCountryId)!;
        this.initiative_idId = document.getElementById(initiative_idId)!;
        this.searchCateId = document.getElementById(searchCateId)!;
        this.searchCategoryValueId = document.getElementById(searchCategoryValueId)!;
        this.searchKeyId = document.getElementById(searchKeyId)!;
        this.homeFirstscreenId = document.getElementById(homeFirstscreenId)!;
        this.keyVisualMainId = document.getElementById(keyVisualMainId)!;
        this.industryEntranceId = document.getElementById(industryEntranceId)!;
        this.userBenefitsId = document.getElementById(userBenefitsId)!;
        this.superdealsEntryId = document.getElementById(superdealsEntryId)!;
        this.brandZoneEntryId = document.getElementById(brandZoneEntryId)!;
        this.industryFloorId = document.getElementById(industryFloorId)!;
        this.emergingStoreEntryId = document.getElementById(emergingStoreEntryId)!;
        this.historyRecordId = document.getElementById(historyRecordId)!;
        this.relatedRecommendEntryId = document.getElementById(relatedRecommendEntryId)!;
        this.alertSubscribeFormId = document.getElementById(alertSubscribeFormId)!;
        this.newuserActivityConfigId = document.getElementById(newuserActivityConfigId)!;
        this.localstorageProxyIfrAlibabadotcomId = document.getElementById(localstorageProxyIfrAlibabadotcomId)!;
        this.criteoTagsDivId = document.getElementById(criteoTagsDivId)!;
        this.googGtTtId = document.getElementById(googGtTtId)!;
        this._oid_ifr_Id = document.getElementById(_oid_ifr_Id)!;

        this.dataLocale = $("[data-locale]");
        this.dataSpm = $("[data-spm]");
        this.dataGrCSLoaded = $("[data-gr-c-s-loaded]");
        this.dataWidgetCid = $("[data-widget-cid]");
        this.dataRole = $("[data-role]");
        this.dataSite = $("[data-site]");
        this.dataPath = $("[data-path]");
        this.dataOrder = $("[data-order]");
        this.dataLoaded = $("[data-loaded]");
        this.dataSrc = $("[data-src]");
        this.dataStat = $("[data-stat]");
        this.dataWidgetid = $("[data-widgetid]");
        this.dataSpaSurvive = $("[data-spa-survive]");
        this.dataTest = $("[data-test]");
        this.dataDealsLink = $("[data-deals-link]");
        this.dataIswintertime = $("[data-iswintertime]");
        this.dataPhase = $("[data-phase]");
        this.dataWidgetId = $("[data-widget-id]");
        this.dataEmailerror = $("[data-emailerror]");
        this.dataFailtips = $("[data-failtips]");
        this.dataSuccesstips = $("[data-successtips]");
        this.dataIsshowspecificuserdialog = $("[data-isshowspecificuserdialog]");
        this.dataAnimateimg = $("[data-animateimg]");
        this.dataBtntext = $("[data-btntext]");
        this.dataCouponTitle = $("[data-coupon-title]");
        this.dataDenomination = $("[data-denomination]");
        this.dataFrequency = $("[data-frequency]");
        this.dataLayerbg = $("[data-layerbg]");
        this.dataLink = $("[data-link]");
        this.dataPromotionname = $("[data-promotionname]");
        this.dataSubtitle = $("[data-subtitle]");
        this.dataTipsTitle = $("[data-tips-title]");
        this.dataTitle = $("[data-title]");
        this.dataSpmAnchorId = $("[data-spm-anchor-id]");
        this.dataSpmActId = $("[data-spm-act-id]");

        console.error('alliExpress not implemented');
    }
}
