import { youtube } from "./youtube";

var mmenu_initId : string;
var mm1Id : string;
var mm2Id : string;
var mm3Id : string;
var admin_traka_51191security_propsxId : string;
var mm4Id : string;
var mm5Id : string;
var mm6Id : string;
var mm7Id : string;
var mm8Id : string;
var mm9Id : string;
var mm10Id : string;
var mm11Id : string;
var mm12Id : string;
var mm13Id : string;
var mm14Id : string;
var mm0Id : string;
var ap2_v1submitformId : string;
var container_admin_barId : string;
var cms_area_admin_barId : string;
var bsAdminNavbarCollapseId : string;
var container_contentId : string;
var defaultHeaderId : string;
var cms_area_horizontal_navId : string;
var nav_101433Id : string;
var cms_area_carouselId : string;
var cms_area_carousel_2Id : string;
var uniboxSuggestBoxId : string;
var uniboxInvisibleId : string;
var cms_area_middleId : string;
var left_sidebarId : string;
var cms_area_leftId : string;
var nav_101432Id : string;
var nav_101432_1Id : string;
var nav_101432_3Id : string;
var nav_101432_8Id : string;
var cms_area_rightId : string;
var subscribe_homeId : string;
var subscribe_mailId : string;
var sub4Id : string;
var mail4Id : string;
var subscription_51196showAllxId : string;
var notyHolderId : string;
var footerMainId : string;
var logo_imgId : string;
var copyrightId : string;
var mmBlockerId : string;

var dataGrCSLoaded : string;
var dataTarget : string;
var dataToggle : string;
var dataParams : string;
var dataSubChecker : string;
var dataMailChecker : string;

export class intranet {

    public youtube: youtube;

    public mmenu_initId: HTMLElement;
    public mm1Id: HTMLElement;
    public mm2Id: HTMLElement;
    public mm3Id: HTMLElement;
    public admin_traka_51191security_propsxId: HTMLElement;
    public mm4Id: HTMLElement;
    public mm5Id: HTMLElement;
    public mm6Id: HTMLElement;
    public mm7Id: HTMLElement;
    public mm8Id: HTMLElement;
    public mm9Id: HTMLElement;
    public mm10Id: HTMLElement;
    public mm11Id: HTMLElement;
    public mm12Id: HTMLElement;
    public mm13Id: HTMLElement;
    public mm14Id: HTMLElement;
    public mm0Id: HTMLElement;
    public ap2_v1submitformId: HTMLElement;
    public container_admin_barId: HTMLElement;
    public cms_area_admin_barId: HTMLElement;
    public bsAdminNavbarCollapseId: HTMLElement;
    public container_contentId: HTMLElement;
    public defaultHeaderId: HTMLElement;
    public cms_area_horizontal_navId: HTMLElement;
    public nav_101433Id: HTMLElement;
    public cms_area_carouselId: HTMLElement;
    public cms_area_carousel_2Id: HTMLElement;
    public uniboxSuggestBoxId: HTMLElement;
    public uniboxInvisibleId: HTMLElement;
    public cms_area_middleId: HTMLElement;
    public left_sidebarId: HTMLElement;
    public cms_area_leftId: HTMLElement;
    public nav_101432Id: HTMLElement;
    public nav_101432_1Id: HTMLElement;
    public nav_101432_3Id: HTMLElement;
    public nav_101432_8Id: HTMLElement;
    public cms_area_rightId: HTMLElement;
    public subscribe_homeId: HTMLElement;
    public subscribe_mailId: HTMLElement;
    public sub4Id: HTMLElement;
    public mail4Id: HTMLElement;
    public subscription_51196showAllxId: HTMLElement;
    public notyHolderId: HTMLElement;
    public footerMainId: HTMLElement;
    public logo_imgId: HTMLElement;
    public copyrightId: HTMLElement;
    public mmBlockerId: HTMLElement;

    public dataGrCSLoaded: JQuery<HTMLElement>;
    public dataTarget: JQuery<HTMLElement>;
    public dataToggle: JQuery<HTMLElement>;
    public dataParams: JQuery<HTMLElement>;
    public dataSubChecker: JQuery<HTMLElement>;
    public dataMailChecker: JQuery<HTMLElement>;

    public constructor() {
        this.youtube = new youtube();

        this.mmenu_initId = document.getElementById(mmenu_initId)!;
        this.mm1Id = document.getElementById(mm1Id)!;
        this.mm2Id = document.getElementById(mm2Id)!;
        this.mm3Id = document.getElementById(mm3Id)!;
        this.admin_traka_51191security_propsxId = document.getElementById(admin_traka_51191security_propsxId)!;
        this.mm4Id = document.getElementById(mm4Id)!;
        this.mm5Id = document.getElementById(mm5Id)!;
        this.mm6Id = document.getElementById(mm6Id)!;
        this.mm7Id = document.getElementById(mm7Id)!;
        this.mm8Id = document.getElementById(mm8Id)!;
        this.mm9Id = document.getElementById(mm9Id)!;
        this.mm10Id = document.getElementById(mm10Id)!;
        this.mm11Id = document.getElementById(mm11Id)!;
        this.mm12Id = document.getElementById(mm12Id)!;
        this.mm13Id = document.getElementById(mm13Id)!;
        this.mm14Id = document.getElementById(mm14Id)!;
        this.mm0Id = document.getElementById(mm0Id)!;
        this.ap2_v1submitformId = document.getElementById(ap2_v1submitformId)!;
        this.container_admin_barId = document.getElementById(container_admin_barId)!;
        this.cms_area_admin_barId = document.getElementById(cms_area_admin_barId)!;
        this.bsAdminNavbarCollapseId = document.getElementById(bsAdminNavbarCollapseId)!;
        this.container_contentId = document.getElementById(container_contentId)!;
        this.defaultHeaderId = document.getElementById(defaultHeaderId)!;
        this.cms_area_horizontal_navId = document.getElementById(cms_area_horizontal_navId)!;
        this.nav_101433Id = document.getElementById(nav_101433Id)!;
        this.cms_area_carouselId = document.getElementById(cms_area_carouselId)!;
        this.cms_area_carousel_2Id = document.getElementById(cms_area_carousel_2Id)!;
        this.uniboxSuggestBoxId = document.getElementById(uniboxSuggestBoxId)!;
        this.uniboxInvisibleId = document.getElementById(uniboxInvisibleId)!;
        this.cms_area_middleId = document.getElementById(cms_area_middleId)!;
        this.left_sidebarId = document.getElementById(left_sidebarId)!;
        this.cms_area_leftId = document.getElementById(cms_area_leftId)!;
        this.nav_101432Id = document.getElementById(nav_101432Id)!;
        this.nav_101432_1Id = document.getElementById(nav_101432_1Id)!;
        this.nav_101432_3Id = document.getElementById(nav_101432_3Id)!;
        this.nav_101432_8Id = document.getElementById(nav_101432_8Id)!;
        this.cms_area_rightId = document.getElementById(cms_area_rightId)!;
        this.subscribe_homeId = document.getElementById(subscribe_homeId)!;
        this.subscribe_mailId = document.getElementById(subscribe_mailId)!;
        this.sub4Id = document.getElementById(sub4Id)!;
        this.mail4Id = document.getElementById(mail4Id)!;
        this.subscription_51196showAllxId = document.getElementById(subscription_51196showAllxId)!;
        this.notyHolderId = document.getElementById(notyHolderId)!;
        this.footerMainId = document.getElementById(footerMainId)!;
        this.logo_imgId = document.getElementById(logo_imgId)!;
        this.copyrightId = document.getElementById(copyrightId)!;
        this.mmBlockerId = document.getElementById(mmBlockerId)!;

        this.dataGrCSLoaded = $("[data-gr-c-s-loaded]");
        this.dataTarget = $("[data-target]");
        this.dataToggle = $("[data-toggle]");
        this.dataParams = $("[data-params]");
        this.dataSubChecker = $("[data-sub-checker]");
        this.dataMailChecker = $("[data-mail-checker]");

        console.error('intranet not implemented');
    }
}
