var yui_3_17_2_1_1519927447765_8Id : string;
var yui_3_17_2_1_1519927447765_9Id : string;
var yui_3_17_2_1_1519927447765_25Id : string;
var yui_3_17_2_1_1519927447765_27Id : string;
var yui_3_17_2_1_1519927447765_86Id : string;
var yui_3_17_2_1_1519927447765_97Id : string;
var firstthemesheetId : string;
var pageSiteIndexId : string;
var yui3CssStampId : string;
var _5a9840971eddbId : string;
var id_q_5a9840971eddbId : string;
var pageId : string;
var pageHeaderId : string;
var pageNavbarId : string;
var navbarLabelId : string;
var courseHeaderId : string;
var pageContentId : string;
var regionMainBoxId : string;
var regionMainId : string;
var userNotificationsId : string;
var maincontentId : string;
var module59836Id : string;
var module13085Id : string;
var module79525Id : string;
var frontpageCategoryNamesId : string;
var skipcategoriesId : string;
var blockRegionSidePreId : string;
var fsb1Id : string;
var inst29630Id : string;
var yui_3_17_2_1_1519927447765_37Id : string;
var instance29630HeaderId : string;
var label_1_1Id : string;
var random5a9840971549e1_groupId : string;
var label_2_3Id : string;
var label_2_4Id : string;
var label_2_5Id : string;
var label_2_6Id : string;
var label_2_7Id : string;
var label_2_8Id : string;
var label_2_13Id : string;
var label_2_14Id : string;
var label_2_15Id : string;
var label_2_17Id : string;
var label_2_19Id : string;
var expandable_branch_0_coursesId : string;
var label_2_20Id : string;
var sb1Id : string;
var fsb3Id : string;
var inst1Id : string;
var yui_3_17_2_1_1519927447765_55Id : string;
var instance1HeaderId : string;
var sb3Id : string;
var blockRegionSidePostId : string;
var fsb5Id : string;
var inst918Id : string;
var yui_3_17_2_1_1519927447765_73Id : string;
var instance918HeaderId : string;
var loginId : string;
var login_usernameId : string;
var login_passwordId : string;
var sb5Id : string;
var inst4Id : string;
var pageFooterId : string;
var courseFooterId : string;

var dataRequirecontext : string;
var dataRequiremodule : string;
var dataGrCSLoaded : string;
var dataToggle : string;
var dataTarget : string;
var dataCategoryid : string;
var dataDepth : string;
var dataShowcourses : string;
var dataType : string;
var dataBlockregion : string;
var dataDroptarget : string;
var dataBlock : string;
var dataInstanceid : string;
var dataAjaxLoader : string;
var dataCollapsible : string;
var dataRequiresAjax : string;
var dataLoaded : string;
var dataNodeId : string;
var dataNodeKey : string;
var dataNodeType : string;

export class moodle {

    public yui_3_17_2_1_1519927447765_8Id: HTMLElement;
    public yui_3_17_2_1_1519927447765_9Id: HTMLElement;
    public yui_3_17_2_1_1519927447765_25Id: HTMLElement;
    public yui_3_17_2_1_1519927447765_27Id: HTMLElement;
    public yui_3_17_2_1_1519927447765_86Id: HTMLElement;
    public yui_3_17_2_1_1519927447765_97Id: HTMLElement;
    public firstthemesheetId: HTMLElement;
    public pageSiteIndexId: HTMLElement;
    public yui3CssStampId: HTMLElement;
    public _5a9840971eddbId: HTMLElement;
    public id_q_5a9840971eddbId: HTMLElement;
    public pageId: HTMLElement;
    public pageHeaderId: HTMLElement;
    public pageNavbarId: HTMLElement;
    public navbarLabelId: HTMLElement;
    public courseHeaderId: HTMLElement;
    public pageContentId: HTMLElement;
    public regionMainBoxId: HTMLElement;
    public regionMainId: HTMLElement;
    public userNotificationsId: HTMLElement;
    public maincontentId: HTMLElement;
    public module59836Id: HTMLElement;
    public module13085Id: HTMLElement;
    public module79525Id: HTMLElement;
    public frontpageCategoryNamesId: HTMLElement;
    public skipcategoriesId: HTMLElement;
    public blockRegionSidePreId: HTMLElement;
    public fsb1Id: HTMLElement;
    public inst29630Id: HTMLElement;
    public yui_3_17_2_1_1519927447765_37Id: HTMLElement;
    public instance29630HeaderId: HTMLElement;
    public label_1_1Id: HTMLElement;
    public random5a9840971549e1_groupId: HTMLElement;
    public label_2_3Id: HTMLElement;
    public label_2_4Id: HTMLElement;
    public label_2_5Id: HTMLElement;
    public label_2_6Id: HTMLElement;
    public label_2_7Id: HTMLElement;
    public label_2_8Id: HTMLElement;
    public label_2_13Id: HTMLElement;
    public label_2_14Id: HTMLElement;
    public label_2_15Id: HTMLElement;
    public label_2_17Id: HTMLElement;
    public label_2_19Id: HTMLElement;
    public expandable_branch_0_coursesId: HTMLElement;
    public label_2_20Id: HTMLElement;
    public sb1Id: HTMLElement;
    public fsb3Id: HTMLElement;
    public inst1Id: HTMLElement;
    public yui_3_17_2_1_1519927447765_55Id: HTMLElement;
    public instance1HeaderId: HTMLElement;
    public sb3Id: HTMLElement;
    public blockRegionSidePostId: HTMLElement;
    public fsb5Id: HTMLElement;
    public inst918Id: HTMLElement;
    public yui_3_17_2_1_1519927447765_73Id: HTMLElement;
    public instance918HeaderId: HTMLElement;
    public loginId: HTMLElement;
    public login_usernameId: HTMLElement;
    public login_passwordId: HTMLElement;
    public sb5Id: HTMLElement;
    public inst4Id: HTMLElement;
    public pageFooterId: HTMLElement;
    public courseFooterId: HTMLElement;

    public dataRequirecontext: JQuery<HTMLElement>;
    public dataRequiremodule: JQuery<HTMLElement>;
    public dataGrCSLoaded: JQuery<HTMLElement>;
    public dataToggle: JQuery<HTMLElement>;
    public dataTarget: JQuery<HTMLElement>;
    public dataCategoryid: JQuery<HTMLElement>;
    public dataDepth: JQuery<HTMLElement>;
    public dataShowcourses: JQuery<HTMLElement>;
    public dataType: JQuery<HTMLElement>;
    public dataBlockregion: JQuery<HTMLElement>;
    public dataDroptarget: JQuery<HTMLElement>;
    public dataBlock: JQuery<HTMLElement>;
    public dataInstanceid: JQuery<HTMLElement>;
    public dataAjaxLoader: JQuery<HTMLElement>;
    public dataCollapsible: JQuery<HTMLElement>;
    public dataRequiresAjax: JQuery<HTMLElement>;
    public dataLoaded: JQuery<HTMLElement>;
    public dataNodeId: JQuery<HTMLElement>;
    public dataNodeKey: JQuery<HTMLElement>;
    public dataNodeType: JQuery<HTMLElement>;

    public constructor() {
        this.yui_3_17_2_1_1519927447765_8Id = document.getElementById(yui_3_17_2_1_1519927447765_8Id)!;
        this.yui_3_17_2_1_1519927447765_9Id = document.getElementById(yui_3_17_2_1_1519927447765_9Id)!;
        this.yui_3_17_2_1_1519927447765_25Id = document.getElementById(yui_3_17_2_1_1519927447765_25Id)!;
        this.yui_3_17_2_1_1519927447765_27Id = document.getElementById(yui_3_17_2_1_1519927447765_27Id)!;
        this.yui_3_17_2_1_1519927447765_86Id = document.getElementById(yui_3_17_2_1_1519927447765_86Id)!;
        this.yui_3_17_2_1_1519927447765_97Id = document.getElementById(yui_3_17_2_1_1519927447765_97Id)!;
        this.firstthemesheetId = document.getElementById(firstthemesheetId)!;
        this.pageSiteIndexId = document.getElementById(pageSiteIndexId)!;
        this.yui3CssStampId = document.getElementById(yui3CssStampId)!;
        this._5a9840971eddbId = document.getElementById(_5a9840971eddbId)!;
        this.id_q_5a9840971eddbId = document.getElementById(id_q_5a9840971eddbId)!;
        this.pageId = document.getElementById(pageId)!;
        this.pageHeaderId = document.getElementById(pageHeaderId)!;
        this.pageNavbarId = document.getElementById(pageNavbarId)!;
        this.navbarLabelId = document.getElementById(navbarLabelId)!;
        this.courseHeaderId = document.getElementById(courseHeaderId)!;
        this.pageContentId = document.getElementById(pageContentId)!;
        this.regionMainBoxId = document.getElementById(regionMainBoxId)!;
        this.regionMainId = document.getElementById(regionMainId)!;
        this.userNotificationsId = document.getElementById(userNotificationsId)!;
        this.maincontentId = document.getElementById(maincontentId)!;
        this.module59836Id = document.getElementById(module59836Id)!;
        this.module13085Id = document.getElementById(module13085Id)!;
        this.module79525Id = document.getElementById(module79525Id)!;
        this.frontpageCategoryNamesId = document.getElementById(frontpageCategoryNamesId)!;
        this.skipcategoriesId = document.getElementById(skipcategoriesId)!;
        this.blockRegionSidePreId = document.getElementById(blockRegionSidePreId)!;
        this.fsb1Id = document.getElementById(fsb1Id)!;
        this.inst29630Id = document.getElementById(inst29630Id)!;
        this.yui_3_17_2_1_1519927447765_37Id = document.getElementById(yui_3_17_2_1_1519927447765_37Id)!;
        this.instance29630HeaderId = document.getElementById(instance29630HeaderId)!;
        this.label_1_1Id = document.getElementById(label_1_1Id)!;
        this.random5a9840971549e1_groupId = document.getElementById(random5a9840971549e1_groupId)!;
        this.label_2_3Id = document.getElementById(label_2_3Id)!;
        this.label_2_4Id = document.getElementById(label_2_4Id)!;
        this.label_2_5Id = document.getElementById(label_2_5Id)!;
        this.label_2_6Id = document.getElementById(label_2_6Id)!;
        this.label_2_7Id = document.getElementById(label_2_7Id)!;
        this.label_2_8Id = document.getElementById(label_2_8Id)!;
        this.label_2_13Id = document.getElementById(label_2_13Id)!;
        this.label_2_14Id = document.getElementById(label_2_14Id)!;
        this.label_2_15Id = document.getElementById(label_2_15Id)!;
        this.label_2_17Id = document.getElementById(label_2_17Id)!;
        this.label_2_19Id = document.getElementById(label_2_19Id)!;
        this.expandable_branch_0_coursesId = document.getElementById(expandable_branch_0_coursesId)!;
        this.label_2_20Id = document.getElementById(label_2_20Id)!;
        this.sb1Id = document.getElementById(sb1Id)!;
        this.fsb3Id = document.getElementById(fsb3Id)!;
        this.inst1Id = document.getElementById(inst1Id)!;
        this.yui_3_17_2_1_1519927447765_55Id = document.getElementById(yui_3_17_2_1_1519927447765_55Id)!;
        this.instance1HeaderId = document.getElementById(instance1HeaderId)!;
        this.sb3Id = document.getElementById(sb3Id)!;
        this.blockRegionSidePostId = document.getElementById(blockRegionSidePostId)!;
        this.fsb5Id = document.getElementById(fsb5Id)!;
        this.inst918Id = document.getElementById(inst918Id)!;
        this.yui_3_17_2_1_1519927447765_73Id = document.getElementById(yui_3_17_2_1_1519927447765_73Id)!;
        this.instance918HeaderId = document.getElementById(instance918HeaderId)!;
        this.loginId = document.getElementById(loginId)!;
        this.login_usernameId = document.getElementById(login_usernameId)!;
        this.login_passwordId = document.getElementById(login_passwordId)!;
        this.sb5Id = document.getElementById(sb5Id)!;
        this.inst4Id = document.getElementById(inst4Id)!;
        this.pageFooterId = document.getElementById(pageFooterId)!;
        this.courseFooterId = document.getElementById(courseFooterId)!;

        this.dataRequirecontext = $("[data-requirecontext]");
        this.dataRequiremodule = $("[data-requiremodule]");
        this.dataGrCSLoaded = $("[data-gr-c-s-loaded]");
        this.dataToggle = $("[data-toggle]");
        this.dataTarget = $("[data-target]");
        this.dataCategoryid = $("[data-categoryid]");
        this.dataDepth = $("[data-depth]");
        this.dataShowcourses = $("[data-showcourses]");
        this.dataType = $("[data-type]");
        this.dataBlockregion = $("[data-blockregion]");
        this.dataDroptarget = $("[data-droptarget]");
        this.dataBlock = $("[data-block]");
        this.dataInstanceid = $("[data-instanceid]");
        this.dataAjaxLoader = $("[data-ajax-loader]");
        this.dataCollapsible = $("[data-collapsible]");
        this.dataRequiresAjax = $("[data-requires-ajax]");
        this.dataLoaded = $("[data-loaded]");
        this.dataNodeId = $("[data-node-id]");
        this.dataNodeKey = $("[data-node-key]");
        this.dataNodeType = $("[data-node-type]");

        console.error('moodle not implemented');
    }
}
