var playerCssId : string;
var extStylesId : string;
var playerId : string;
var playerApiId : string;
var guideServiceId : string;
var navId : string;
var netId : string;
var visibilityMonitorId : string;
var historyManagerId : string;
var contentId : string;
var mastheadContainerId : string;
var mastheadId : string;
var tickerId : string;
var interstitialId : string;
var containerId : string;
var backButtonId : string;
var backButtonTooltipId : string;
var guideButtonId : string;
var guideIconId : string;
var logoId : string;
var logoIconContainerId : string;
var youtubePathsId : string;
var logoRedIconContainerId : string;
var logoIconId : string;
var logoRedIconId : string;
var countryCodeId : string;
var searchId : string;
var searchFormId : string;
var searchInputId : string;
var searchContainerId : string;
var searchIconId : string;
var tooltipId : string;
var searchIconLegacyId : string;
var endId : string;
var searchButtonId : string;
var buttonsId : string;
var buttonId : string;
var notificationCountId : string;
var avatarBtnId : string;
var imgId : string;
var pageManagerId : string;
var miniplayerBarId : string;
var topId : string;
var playerContainerId : string;
var ytdPlayerId : string;
var movie_playerId : string;
var atr_challengeId : string;
var ytpId3Id : string;
var ytpId4Id : string;
var ytpId7Id : string;
var ytpId8Id : string;
var ytpId1Id : string;
var ytpId167Id : string;
var ytpId27Id : string;
var ytpId2Id : string;
var ytpId6Id : string;
var ytpId5Id : string;
var ytpId18Id : string;
var ytpId9Id : string;
var ytpId10Id : string;
var ytpId11Id : string;
var ytpId197Id : string;
var ytpId13Id : string;
var ytpSvgVolumeAnimationMaskId : string;
var ytpSvgVolumeAnimationSlashMaskId : string;
var ytpId15Id : string;
var ytpId16Id : string;
var ytpId17Id : string;
var ytpId19Id : string;
var ytpId20Id : string;
var ytpId21Id : string;
var ytpId22Id : string;
var ytpId23Id : string;
var ytpId24Id : string;
var ytpId25Id : string;
var ytpId26Id : string;
var errorScreenId : string;
var playerFocusControlId : string;
var speedygId : string;
var mainId : string;
var playlistId : string;
var transcriptLoaderId : string;
var relatedId : string;
var playerAdsId : string;
var offerModuleId : string;
var itemsId : string;
var headId : string;
var upnextId : string;
var autoplayId : string;
var toggleId : string;
var toggleBarId : string;
var toggleButtonId : string;
var dismissableId : string;
var thumbnailId : string;
var overlaysId : string;
var progressId : string;
var mouseoverOverlayId : string;
var hoverOverlaysId : string;
var videoTitleId : string;
var metadataId : string;
var bylineContainerId : string;
var bylineInnerContainerId : string;
var bylineId : string;
var repeatId : string;
var separatorId : string;
var metadataLineId : string;
var additionalMetadataLineId : string;
var menuId : string;
var topLevelButtonsId : string;
var dismissedId : string;
var titleId : string;
var continuationsId : string;
var spinnerId : string;
var spinnerContainerId : string;
var backgroundId : string;
var wavesId : string;
var relatedSkeletonId : string;
var contentSeparatorId : string;
var alertsId : string;
var messagesId : string;
var clarifyBoxId : string;
var infoId : string;
var infoSkeletonId : string;
var infoContentsId : string;
var countId : string;
var flexId : string;
var menuContainerId : string;
var textId : string;
var sentimentId : string;
var likeBarId : string;
var plaShelfId : string;
var reportId : string;
var reportFormId : string;
var metaId : string;
var metaSkeletonId : string;
var limitedStateId : string;
var metaContentsId : string;
var topRowId : string;
var avatarId : string;
var uploadInfoId : string;
var ownerContainerId : string;
var ownerNameId : string;
var sponsorButtonId : string;
var subscribeButtonId : string;
var watch7SubscriptionContainerId : string;
var notificationButtonId : string;
var descriptionId : string;
var alwaysShownId : string;
var collapsibleId : string;
var lessId : string;
var moreId : string;
var ticketShelfId : string;
var merchShelfId : string;
var commentsId : string;
var headerId : string;
var contentsId : string;
var surveyId : string;
var ytdYouthereDialogWindowId : string;
var ytdYouthereMainId : string;
var ytdYouthereTitleId : string;
var ytdYouthereConfirmButtonId : string;
var mastheadAdId : string;
var primaryId : string;
var subMenuId : string;
var titleContainerId : string;
var imageContainerId : string;
var featuredBadgeId : string;
var titleAnnotationId : string;
var playButtonId : string;
var spacerId : string;
var subtitleId : string;
var leftArrowId : string;
var scrollContainerId : string;
var detailsId : string;
var metadataContainerId : string;
var dismissedContentId : string;
var rightArrowId : string;
var viewAllId : string;
var secondaryId : string;
var resultCountId : string;
var correctedId : string;
var correctedLinkId : string;
var titleWrapperId : string;
var descriptionTextId : string;
var badgesId : string;
var channelTitleId : string;
var subscribersId : string;
var videoCountId : string;
var watchCardHeaderId : string;
var watchCardTitleId : string;
var subtitleRowId : string;
var watchCardLabelsId : string;
var imgEndpointId : string;
var collageId : string;
var sectionLeftId : string;
var sectionRightId : string;
var topRightId : string;
var overlayButtonId : string;
var overlayIconId : string;
var overlayTextId : string;
var tabsId : string;
var iconId : string;
var tabsContainerId : string;
var tabsContentId : string;
var selectionBarId : string;
var viewAllEndpointId : string;
var relatedHeaderId : string;
var relatedItemsId : string;
var guideId : string;
var scrimId : string;
var contentContainerId : string;
var guideWrapperId : string;
var guideSpacerId : string;
var guideContentId : string;
var guideInnerContentId : string;
var guideRendererId : string;
var sectionsId : string;
var guideSectionTitleId : string;
var endpointId : string;
var expanderItemId : string;
var expandedId : string;
var expandableItemsId : string;
var collapserItemId : string;
var footerId : string;
var guideLinksPrimaryId : string;
var guideLinksSecondaryId : string;
var vatNoticeId : string;
var copyrightId : string;
var extraButtonsId : string;
var debugMenuId : string;
var legalHelpPageId : string;
var ytLogoId : string;
var ytLogoRedId : string;
var youtubeRedPathsId : string;

var dataFeature : string;
var dataExpires : string;
var dataGrCSLoaded : string;
var dataVersion : string;
var dataLayer : string;
var dataVisualId : string;
var dataSessionlink : string;
var dataTooltipOpaque : string;
var dataTooltipImage : string;
var dataDuration : string;
var dataPreview : string;
var dataTooltipText : string;
var dataChannelExternalId : string;
var dataClicktracking : string;
var dataStyleType : string;
var dataSubscribedTimestamp : string;
var dataShowUnsubConfirmTimeFrame : string;
var dataShowUnsubConfirmDialog : string;

export class youtube {

    public playerCssId: HTMLElement;
    public extStylesId: HTMLElement;
    public playerId: HTMLElement;
    public playerApiId: HTMLElement;
    public guideServiceId: HTMLElement;
    public navId: HTMLElement;
    public netId: HTMLElement;
    public visibilityMonitorId: HTMLElement;
    public historyManagerId: HTMLElement;
    public contentId: HTMLElement;
    public mastheadContainerId: HTMLElement;
    public mastheadId: HTMLElement;
    public tickerId: HTMLElement;
    public interstitialId: HTMLElement;
    public containerId: HTMLElement;
    public backButtonId: HTMLElement;
    public backButtonTooltipId: HTMLElement;
    public guideButtonId: HTMLElement;
    public guideIconId: HTMLElement;
    public logoId: HTMLElement;
    public logoIconContainerId: HTMLElement;
    public youtubePathsId: HTMLElement;
    public logoRedIconContainerId: HTMLElement;
    public logoIconId: HTMLElement;
    public logoRedIconId: HTMLElement;
    public countryCodeId: HTMLElement;
    public searchId: HTMLElement;
    public searchFormId: HTMLElement;
    public searchInputId: HTMLElement;
    public searchContainerId: HTMLElement;
    public searchIconId: HTMLElement;
    public tooltipId: HTMLElement;
    public searchIconLegacyId: HTMLElement;
    public endId: HTMLElement;
    public searchButtonId: HTMLElement;
    public buttonsId: HTMLElement;
    public buttonId: HTMLElement;
    public notificationCountId: HTMLElement;
    public avatarBtnId: HTMLElement;
    public imgId: HTMLElement;
    public pageManagerId: HTMLElement;
    public miniplayerBarId: HTMLElement;
    public topId: HTMLElement;
    public playerContainerId: HTMLElement;
    public ytdPlayerId: HTMLElement;
    public movie_playerId: HTMLElement;
    public atr_challengeId: HTMLElement;
    public ytpId3Id: HTMLElement;
    public ytpId4Id: HTMLElement;
    public ytpId7Id: HTMLElement;
    public ytpId8Id: HTMLElement;
    public ytpId1Id: HTMLElement;
    public ytpId167Id: HTMLElement;
    public ytpId27Id: HTMLElement;
    public ytpId2Id: HTMLElement;
    public ytpId6Id: HTMLElement;
    public ytpId5Id: HTMLElement;
    public ytpId18Id: HTMLElement;
    public ytpId9Id: HTMLElement;
    public ytpId10Id: HTMLElement;
    public ytpId11Id: HTMLElement;
    public ytpId197Id: HTMLElement;
    public ytpId13Id: HTMLElement;
    public ytpSvgVolumeAnimationMaskId: HTMLElement;
    public ytpSvgVolumeAnimationSlashMaskId: HTMLElement;
    public ytpId15Id: HTMLElement;
    public ytpId16Id: HTMLElement;
    public ytpId17Id: HTMLElement;
    public ytpId19Id: HTMLElement;
    public ytpId20Id: HTMLElement;
    public ytpId21Id: HTMLElement;
    public ytpId22Id: HTMLElement;
    public ytpId23Id: HTMLElement;
    public ytpId24Id: HTMLElement;
    public ytpId25Id: HTMLElement;
    public ytpId26Id: HTMLElement;
    public errorScreenId: HTMLElement;
    public playerFocusControlId: HTMLElement;
    public speedygId: HTMLElement;
    public mainId: HTMLElement;
    public playlistId: HTMLElement;
    public transcriptLoaderId: HTMLElement;
    public relatedId: HTMLElement;
    public playerAdsId: HTMLElement;
    public offerModuleId: HTMLElement;
    public itemsId: HTMLElement;
    public headId: HTMLElement;
    public upnextId: HTMLElement;
    public autoplayId: HTMLElement;
    public toggleId: HTMLElement;
    public toggleBarId: HTMLElement;
    public toggleButtonId: HTMLElement;
    public dismissableId: HTMLElement;
    public thumbnailId: HTMLElement;
    public overlaysId: HTMLElement;
    public progressId: HTMLElement;
    public mouseoverOverlayId: HTMLElement;
    public hoverOverlaysId: HTMLElement;
    public videoTitleId: HTMLElement;
    public metadataId: HTMLElement;
    public bylineContainerId: HTMLElement;
    public bylineInnerContainerId: HTMLElement;
    public bylineId: HTMLElement;
    public repeatId: HTMLElement;
    public separatorId: HTMLElement;
    public metadataLineId: HTMLElement;
    public additionalMetadataLineId: HTMLElement;
    public menuId: HTMLElement;
    public topLevelButtonsId: HTMLElement;
    public dismissedId: HTMLElement;
    public titleId: HTMLElement;
    public continuationsId: HTMLElement;
    public spinnerId: HTMLElement;
    public spinnerContainerId: HTMLElement;
    public backgroundId: HTMLElement;
    public wavesId: HTMLElement;
    public relatedSkeletonId: HTMLElement;
    public contentSeparatorId: HTMLElement;
    public alertsId: HTMLElement;
    public messagesId: HTMLElement;
    public clarifyBoxId: HTMLElement;
    public infoId: HTMLElement;
    public infoSkeletonId: HTMLElement;
    public infoContentsId: HTMLElement;
    public countId: HTMLElement;
    public flexId: HTMLElement;
    public menuContainerId: HTMLElement;
    public textId: HTMLElement;
    public sentimentId: HTMLElement;
    public likeBarId: HTMLElement;
    public plaShelfId: HTMLElement;
    public reportId: HTMLElement;
    public reportFormId: HTMLElement;
    public metaId: HTMLElement;
    public metaSkeletonId: HTMLElement;
    public limitedStateId: HTMLElement;
    public metaContentsId: HTMLElement;
    public topRowId: HTMLElement;
    public avatarId: HTMLElement;
    public uploadInfoId: HTMLElement;
    public ownerContainerId: HTMLElement;
    public ownerNameId: HTMLElement;
    public sponsorButtonId: HTMLElement;
    public subscribeButtonId: HTMLElement;
    public watch7SubscriptionContainerId: HTMLElement;
    public notificationButtonId: HTMLElement;
    public descriptionId: HTMLElement;
    public alwaysShownId: HTMLElement;
    public collapsibleId: HTMLElement;
    public lessId: HTMLElement;
    public moreId: HTMLElement;
    public ticketShelfId: HTMLElement;
    public merchShelfId: HTMLElement;
    public commentsId: HTMLElement;
    public headerId: HTMLElement;
    public contentsId: HTMLElement;
    public surveyId: HTMLElement;
    public ytdYouthereDialogWindowId: HTMLElement;
    public ytdYouthereMainId: HTMLElement;
    public ytdYouthereTitleId: HTMLElement;
    public ytdYouthereConfirmButtonId: HTMLElement;
    public mastheadAdId: HTMLElement;
    public primaryId: HTMLElement;
    public subMenuId: HTMLElement;
    public titleContainerId: HTMLElement;
    public imageContainerId: HTMLElement;
    public featuredBadgeId: HTMLElement;
    public titleAnnotationId: HTMLElement;
    public playButtonId: HTMLElement;
    public spacerId: HTMLElement;
    public subtitleId: HTMLElement;
    public leftArrowId: HTMLElement;
    public scrollContainerId: HTMLElement;
    public detailsId: HTMLElement;
    public metadataContainerId: HTMLElement;
    public dismissedContentId: HTMLElement;
    public rightArrowId: HTMLElement;
    public viewAllId: HTMLElement;
    public secondaryId: HTMLElement;
    public resultCountId: HTMLElement;
    public correctedId: HTMLElement;
    public correctedLinkId: HTMLElement;
    public titleWrapperId: HTMLElement;
    public descriptionTextId: HTMLElement;
    public badgesId: HTMLElement;
    public channelTitleId: HTMLElement;
    public subscribersId: HTMLElement;
    public videoCountId: HTMLElement;
    public watchCardHeaderId: HTMLElement;
    public watchCardTitleId: HTMLElement;
    public subtitleRowId: HTMLElement;
    public watchCardLabelsId: HTMLElement;
    public imgEndpointId: HTMLElement;
    public collageId: HTMLElement;
    public sectionLeftId: HTMLElement;
    public sectionRightId: HTMLElement;
    public topRightId: HTMLElement;
    public overlayButtonId: HTMLElement;
    public overlayIconId: HTMLElement;
    public overlayTextId: HTMLElement;
    public tabsId: HTMLElement;
    public iconId: HTMLElement;
    public tabsContainerId: HTMLElement;
    public tabsContentId: HTMLElement;
    public selectionBarId: HTMLElement;
    public viewAllEndpointId: HTMLElement;
    public relatedHeaderId: HTMLElement;
    public relatedItemsId: HTMLElement;
    public guideId: HTMLElement;
    public scrimId: HTMLElement;
    public contentContainerId: HTMLElement;
    public guideWrapperId: HTMLElement;
    public guideSpacerId: HTMLElement;
    public guideContentId: HTMLElement;
    public guideInnerContentId: HTMLElement;
    public guideRendererId: HTMLElement;
    public sectionsId: HTMLElement;
    public guideSectionTitleId: HTMLElement;
    public endpointId: HTMLElement;
    public expanderItemId: HTMLElement;
    public expandedId: HTMLElement;
    public expandableItemsId: HTMLElement;
    public collapserItemId: HTMLElement;
    public footerId: HTMLElement;
    public guideLinksPrimaryId: HTMLElement;
    public guideLinksSecondaryId: HTMLElement;
    public vatNoticeId: HTMLElement;
    public copyrightId: HTMLElement;
    public extraButtonsId: HTMLElement;
    public debugMenuId: HTMLElement;
    public legalHelpPageId: HTMLElement;
    public ytLogoId: HTMLElement;
    public ytLogoRedId: HTMLElement;
    public youtubeRedPathsId: HTMLElement;

    public dataFeature: JQuery<HTMLElement>;
    public dataExpires: JQuery<HTMLElement>;
    public dataGrCSLoaded: JQuery<HTMLElement>;
    public dataVersion: JQuery<HTMLElement>;
    public dataLayer: JQuery<HTMLElement>;
    public dataVisualId: JQuery<HTMLElement>;
    public dataSessionlink: JQuery<HTMLElement>;
    public dataTooltipOpaque: JQuery<HTMLElement>;
    public dataTooltipImage: JQuery<HTMLElement>;
    public dataDuration: JQuery<HTMLElement>;
    public dataPreview: JQuery<HTMLElement>;
    public dataTooltipText: JQuery<HTMLElement>;
    public dataChannelExternalId: JQuery<HTMLElement>;
    public dataClicktracking: JQuery<HTMLElement>;
    public dataStyleType: JQuery<HTMLElement>;
    public dataSubscribedTimestamp: JQuery<HTMLElement>;
    public dataShowUnsubConfirmTimeFrame: JQuery<HTMLElement>;
    public dataShowUnsubConfirmDialog: JQuery<HTMLElement>;

    public constructor() {
        this.playerCssId = document.getElementById(playerCssId)!;
        this.extStylesId = document.getElementById(extStylesId)!;
        this.playerId = document.getElementById(playerId)!;
        this.playerApiId = document.getElementById(playerApiId)!;
        this.guideServiceId = document.getElementById(guideServiceId)!;
        this.navId = document.getElementById(navId)!;
        this.netId = document.getElementById(netId)!;
        this.visibilityMonitorId = document.getElementById(visibilityMonitorId)!;
        this.historyManagerId = document.getElementById(historyManagerId)!;
        this.contentId = document.getElementById(contentId)!;
        this.mastheadContainerId = document.getElementById(mastheadContainerId)!;
        this.mastheadId = document.getElementById(mastheadId)!;
        this.tickerId = document.getElementById(tickerId)!;
        this.interstitialId = document.getElementById(interstitialId)!;
        this.containerId = document.getElementById(containerId)!;
        this.backButtonId = document.getElementById(backButtonId)!;
        this.backButtonTooltipId = document.getElementById(backButtonTooltipId)!;
        this.guideButtonId = document.getElementById(guideButtonId)!;
        this.guideIconId = document.getElementById(guideIconId)!;
        this.logoId = document.getElementById(logoId)!;
        this.logoIconContainerId = document.getElementById(logoIconContainerId)!;
        this.youtubePathsId = document.getElementById(youtubePathsId)!;
        this.logoRedIconContainerId = document.getElementById(logoRedIconContainerId)!;
        this.logoIconId = document.getElementById(logoIconId)!;
        this.logoRedIconId = document.getElementById(logoRedIconId)!;
        this.countryCodeId = document.getElementById(countryCodeId)!;
        this.searchId = document.getElementById(searchId)!;
        this.searchFormId = document.getElementById(searchFormId)!;
        this.searchInputId = document.getElementById(searchInputId)!;
        this.searchContainerId = document.getElementById(searchContainerId)!;
        this.searchIconId = document.getElementById(searchIconId)!;
        this.tooltipId = document.getElementById(tooltipId)!;
        this.searchIconLegacyId = document.getElementById(searchIconLegacyId)!;
        this.endId = document.getElementById(endId)!;
        this.searchButtonId = document.getElementById(searchButtonId)!;
        this.buttonsId = document.getElementById(buttonsId)!;
        this.buttonId = document.getElementById(buttonId)!;
        this.notificationCountId = document.getElementById(notificationCountId)!;
        this.avatarBtnId = document.getElementById(avatarBtnId)!;
        this.imgId = document.getElementById(imgId)!;
        this.pageManagerId = document.getElementById(pageManagerId)!;
        this.miniplayerBarId = document.getElementById(miniplayerBarId)!;
        this.topId = document.getElementById(topId)!;
        this.playerContainerId = document.getElementById(playerContainerId)!;
        this.ytdPlayerId = document.getElementById(ytdPlayerId)!;
        this.movie_playerId = document.getElementById(movie_playerId)!;
        this.atr_challengeId = document.getElementById(atr_challengeId)!;
        this.ytpId3Id = document.getElementById(ytpId3Id)!;
        this.ytpId4Id = document.getElementById(ytpId4Id)!;
        this.ytpId7Id = document.getElementById(ytpId7Id)!;
        this.ytpId8Id = document.getElementById(ytpId8Id)!;
        this.ytpId1Id = document.getElementById(ytpId1Id)!;
        this.ytpId167Id = document.getElementById(ytpId167Id)!;
        this.ytpId27Id = document.getElementById(ytpId27Id)!;
        this.ytpId2Id = document.getElementById(ytpId2Id)!;
        this.ytpId6Id = document.getElementById(ytpId6Id)!;
        this.ytpId5Id = document.getElementById(ytpId5Id)!;
        this.ytpId18Id = document.getElementById(ytpId18Id)!;
        this.ytpId9Id = document.getElementById(ytpId9Id)!;
        this.ytpId10Id = document.getElementById(ytpId10Id)!;
        this.ytpId11Id = document.getElementById(ytpId11Id)!;
        this.ytpId197Id = document.getElementById(ytpId197Id)!;
        this.ytpId13Id = document.getElementById(ytpId13Id)!;
        this.ytpSvgVolumeAnimationMaskId = document.getElementById(ytpSvgVolumeAnimationMaskId)!;
        this.ytpSvgVolumeAnimationSlashMaskId = document.getElementById(ytpSvgVolumeAnimationSlashMaskId)!;
        this.ytpId15Id = document.getElementById(ytpId15Id)!;
        this.ytpId16Id = document.getElementById(ytpId16Id)!;
        this.ytpId17Id = document.getElementById(ytpId17Id)!;
        this.ytpId19Id = document.getElementById(ytpId19Id)!;
        this.ytpId20Id = document.getElementById(ytpId20Id)!;
        this.ytpId21Id = document.getElementById(ytpId21Id)!;
        this.ytpId22Id = document.getElementById(ytpId22Id)!;
        this.ytpId23Id = document.getElementById(ytpId23Id)!;
        this.ytpId24Id = document.getElementById(ytpId24Id)!;
        this.ytpId25Id = document.getElementById(ytpId25Id)!;
        this.ytpId26Id = document.getElementById(ytpId26Id)!;
        this.errorScreenId = document.getElementById(errorScreenId)!;
        this.playerFocusControlId = document.getElementById(playerFocusControlId)!;
        this.speedygId = document.getElementById(speedygId)!;
        this.mainId = document.getElementById(mainId)!;
        this.playlistId = document.getElementById(playlistId)!;
        this.transcriptLoaderId = document.getElementById(transcriptLoaderId)!;
        this.relatedId = document.getElementById(relatedId)!;
        this.playerAdsId = document.getElementById(playerAdsId)!;
        this.offerModuleId = document.getElementById(offerModuleId)!;
        this.itemsId = document.getElementById(itemsId)!;
        this.headId = document.getElementById(headId)!;
        this.upnextId = document.getElementById(upnextId)!;
        this.autoplayId = document.getElementById(autoplayId)!;
        this.toggleId = document.getElementById(toggleId)!;
        this.toggleBarId = document.getElementById(toggleBarId)!;
        this.toggleButtonId = document.getElementById(toggleButtonId)!;
        this.dismissableId = document.getElementById(dismissableId)!;
        this.thumbnailId = document.getElementById(thumbnailId)!;
        this.overlaysId = document.getElementById(overlaysId)!;
        this.progressId = document.getElementById(progressId)!;
        this.mouseoverOverlayId = document.getElementById(mouseoverOverlayId)!;
        this.hoverOverlaysId = document.getElementById(hoverOverlaysId)!;
        this.videoTitleId = document.getElementById(videoTitleId)!;
        this.metadataId = document.getElementById(metadataId)!;
        this.bylineContainerId = document.getElementById(bylineContainerId)!;
        this.bylineInnerContainerId = document.getElementById(bylineInnerContainerId)!;
        this.bylineId = document.getElementById(bylineId)!;
        this.repeatId = document.getElementById(repeatId)!;
        this.separatorId = document.getElementById(separatorId)!;
        this.metadataLineId = document.getElementById(metadataLineId)!;
        this.additionalMetadataLineId = document.getElementById(additionalMetadataLineId)!;
        this.menuId = document.getElementById(menuId)!;
        this.topLevelButtonsId = document.getElementById(topLevelButtonsId)!;
        this.dismissedId = document.getElementById(dismissedId)!;
        this.titleId = document.getElementById(titleId)!;
        this.continuationsId = document.getElementById(continuationsId)!;
        this.spinnerId = document.getElementById(spinnerId)!;
        this.spinnerContainerId = document.getElementById(spinnerContainerId)!;
        this.backgroundId = document.getElementById(backgroundId)!;
        this.wavesId = document.getElementById(wavesId)!;
        this.relatedSkeletonId = document.getElementById(relatedSkeletonId)!;
        this.contentSeparatorId = document.getElementById(contentSeparatorId)!;
        this.alertsId = document.getElementById(alertsId)!;
        this.messagesId = document.getElementById(messagesId)!;
        this.clarifyBoxId = document.getElementById(clarifyBoxId)!;
        this.infoId = document.getElementById(infoId)!;
        this.infoSkeletonId = document.getElementById(infoSkeletonId)!;
        this.infoContentsId = document.getElementById(infoContentsId)!;
        this.countId = document.getElementById(countId)!;
        this.flexId = document.getElementById(flexId)!;
        this.menuContainerId = document.getElementById(menuContainerId)!;
        this.textId = document.getElementById(textId)!;
        this.sentimentId = document.getElementById(sentimentId)!;
        this.likeBarId = document.getElementById(likeBarId)!;
        this.plaShelfId = document.getElementById(plaShelfId)!;
        this.reportId = document.getElementById(reportId)!;
        this.reportFormId = document.getElementById(reportFormId)!;
        this.metaId = document.getElementById(metaId)!;
        this.metaSkeletonId = document.getElementById(metaSkeletonId)!;
        this.limitedStateId = document.getElementById(limitedStateId)!;
        this.metaContentsId = document.getElementById(metaContentsId)!;
        this.topRowId = document.getElementById(topRowId)!;
        this.avatarId = document.getElementById(avatarId)!;
        this.uploadInfoId = document.getElementById(uploadInfoId)!;
        this.ownerContainerId = document.getElementById(ownerContainerId)!;
        this.ownerNameId = document.getElementById(ownerNameId)!;
        this.sponsorButtonId = document.getElementById(sponsorButtonId)!;
        this.subscribeButtonId = document.getElementById(subscribeButtonId)!;
        this.watch7SubscriptionContainerId = document.getElementById(watch7SubscriptionContainerId)!;
        this.notificationButtonId = document.getElementById(notificationButtonId)!;
        this.descriptionId = document.getElementById(descriptionId)!;
        this.alwaysShownId = document.getElementById(alwaysShownId)!;
        this.collapsibleId = document.getElementById(collapsibleId)!;
        this.lessId = document.getElementById(lessId)!;
        this.moreId = document.getElementById(moreId)!;
        this.ticketShelfId = document.getElementById(ticketShelfId)!;
        this.merchShelfId = document.getElementById(merchShelfId)!;
        this.commentsId = document.getElementById(commentsId)!;
        this.headerId = document.getElementById(headerId)!;
        this.contentsId = document.getElementById(contentsId)!;
        this.surveyId = document.getElementById(surveyId)!;
        this.ytdYouthereDialogWindowId = document.getElementById(ytdYouthereDialogWindowId)!;
        this.ytdYouthereMainId = document.getElementById(ytdYouthereMainId)!;
        this.ytdYouthereTitleId = document.getElementById(ytdYouthereTitleId)!;
        this.ytdYouthereConfirmButtonId = document.getElementById(ytdYouthereConfirmButtonId)!;
        this.mastheadAdId = document.getElementById(mastheadAdId)!;
        this.primaryId = document.getElementById(primaryId)!;
        this.subMenuId = document.getElementById(subMenuId)!;
        this.titleContainerId = document.getElementById(titleContainerId)!;
        this.imageContainerId = document.getElementById(imageContainerId)!;
        this.featuredBadgeId = document.getElementById(featuredBadgeId)!;
        this.titleAnnotationId = document.getElementById(titleAnnotationId)!;
        this.playButtonId = document.getElementById(playButtonId)!;
        this.spacerId = document.getElementById(spacerId)!;
        this.subtitleId = document.getElementById(subtitleId)!;
        this.leftArrowId = document.getElementById(leftArrowId)!;
        this.scrollContainerId = document.getElementById(scrollContainerId)!;
        this.detailsId = document.getElementById(detailsId)!;
        this.metadataContainerId = document.getElementById(metadataContainerId)!;
        this.dismissedContentId = document.getElementById(dismissedContentId)!;
        this.rightArrowId = document.getElementById(rightArrowId)!;
        this.viewAllId = document.getElementById(viewAllId)!;
        this.secondaryId = document.getElementById(secondaryId)!;
        this.resultCountId = document.getElementById(resultCountId)!;
        this.correctedId = document.getElementById(correctedId)!;
        this.correctedLinkId = document.getElementById(correctedLinkId)!;
        this.titleWrapperId = document.getElementById(titleWrapperId)!;
        this.descriptionTextId = document.getElementById(descriptionTextId)!;
        this.badgesId = document.getElementById(badgesId)!;
        this.channelTitleId = document.getElementById(channelTitleId)!;
        this.subscribersId = document.getElementById(subscribersId)!;
        this.videoCountId = document.getElementById(videoCountId)!;
        this.watchCardHeaderId = document.getElementById(watchCardHeaderId)!;
        this.watchCardTitleId = document.getElementById(watchCardTitleId)!;
        this.subtitleRowId = document.getElementById(subtitleRowId)!;
        this.watchCardLabelsId = document.getElementById(watchCardLabelsId)!;
        this.imgEndpointId = document.getElementById(imgEndpointId)!;
        this.collageId = document.getElementById(collageId)!;
        this.sectionLeftId = document.getElementById(sectionLeftId)!;
        this.sectionRightId = document.getElementById(sectionRightId)!;
        this.topRightId = document.getElementById(topRightId)!;
        this.overlayButtonId = document.getElementById(overlayButtonId)!;
        this.overlayIconId = document.getElementById(overlayIconId)!;
        this.overlayTextId = document.getElementById(overlayTextId)!;
        this.tabsId = document.getElementById(tabsId)!;
        this.iconId = document.getElementById(iconId)!;
        this.tabsContainerId = document.getElementById(tabsContainerId)!;
        this.tabsContentId = document.getElementById(tabsContentId)!;
        this.selectionBarId = document.getElementById(selectionBarId)!;
        this.viewAllEndpointId = document.getElementById(viewAllEndpointId)!;
        this.relatedHeaderId = document.getElementById(relatedHeaderId)!;
        this.relatedItemsId = document.getElementById(relatedItemsId)!;
        this.guideId = document.getElementById(guideId)!;
        this.scrimId = document.getElementById(scrimId)!;
        this.contentContainerId = document.getElementById(contentContainerId)!;
        this.guideWrapperId = document.getElementById(guideWrapperId)!;
        this.guideSpacerId = document.getElementById(guideSpacerId)!;
        this.guideContentId = document.getElementById(guideContentId)!;
        this.guideInnerContentId = document.getElementById(guideInnerContentId)!;
        this.guideRendererId = document.getElementById(guideRendererId)!;
        this.sectionsId = document.getElementById(sectionsId)!;
        this.guideSectionTitleId = document.getElementById(guideSectionTitleId)!;
        this.endpointId = document.getElementById(endpointId)!;
        this.expanderItemId = document.getElementById(expanderItemId)!;
        this.expandedId = document.getElementById(expandedId)!;
        this.expandableItemsId = document.getElementById(expandableItemsId)!;
        this.collapserItemId = document.getElementById(collapserItemId)!;
        this.footerId = document.getElementById(footerId)!;
        this.guideLinksPrimaryId = document.getElementById(guideLinksPrimaryId)!;
        this.guideLinksSecondaryId = document.getElementById(guideLinksSecondaryId)!;
        this.vatNoticeId = document.getElementById(vatNoticeId)!;
        this.copyrightId = document.getElementById(copyrightId)!;
        this.extraButtonsId = document.getElementById(extraButtonsId)!;
        this.debugMenuId = document.getElementById(debugMenuId)!;
        this.legalHelpPageId = document.getElementById(legalHelpPageId)!;
        this.ytLogoId = document.getElementById(ytLogoId)!;
        this.ytLogoRedId = document.getElementById(ytLogoRedId)!;
        this.youtubeRedPathsId = document.getElementById(youtubeRedPathsId)!;

        this.dataFeature = $("[data-feature]");
        this.dataExpires = $("[data-expires]");
        this.dataGrCSLoaded = $("[data-gr-c-s-loaded]");
        this.dataVersion = $("[data-version]");
        this.dataLayer = $("[data-layer]");
        this.dataVisualId = $("[data-visual-id]");
        this.dataSessionlink = $("[data-sessionlink]");
        this.dataTooltipOpaque = $("[data-tooltip-opaque]");
        this.dataTooltipImage = $("[data-tooltip-image]");
        this.dataDuration = $("[data-duration]");
        this.dataPreview = $("[data-preview]");
        this.dataTooltipText = $("[data-tooltip-text]");
        this.dataChannelExternalId = $("[data-channel-external-id]");
        this.dataClicktracking = $("[data-clicktracking]");
        this.dataStyleType = $("[data-style-type]");
        this.dataSubscribedTimestamp = $("[data-subscribed-timestamp]");
        this.dataShowUnsubConfirmTimeFrame = $("[data-show-unsub-confirm-time-frame]");
        this.dataShowUnsubConfirmDialog = $("[data-show-unsub-confirm-dialog]");

        console.error('youtube not implemented');
    }
}
